#!/usr/bin/env bash
set -euo pipefail

# Upload screenshot PNGs to GitHub as release assets and print markdown image
# syntax that can be pasted into a PR comment.
#
# Usage:
#   upload-screenshots.sh <repo> <pr-number> <file1.png> [file2.png ...]
#
# Example:
#   IMAGES=$(upload-screenshots.sh islo-labs/islo-frontend 207 /tmp/verify-*.png)
#   gh pr comment 207 --repo islo-labs/islo-frontend --body "Report\n${IMAGES}"

REPO="${1:?Usage: upload-screenshots.sh <repo> <pr-number> <file ...>}"
PR="${2:?Usage: upload-screenshots.sh <repo> <pr-number> <file ...>}"
shift 2

if [ $# -eq 0 ]; then
  echo "No files to upload" >&2
  exit 0
fi

TAG="verify-pr-${PR}-$(date +%s)"

gh release create "$TAG" "$@" \
  --repo "$REPO" \
  --title "Verify screenshots — PR #${PR}" \
  --notes "Auto-generated by islo-verify. Safe to delete after PR is closed." \
  --prerelease >/dev/null 2>&1

ASSETS=$(gh api "repos/${REPO}/releases/tags/${TAG}" \
  --jq '.assets[] | "![" + .name + "](" + .browser_download_url + ")"')

echo "$ASSETS"
